### ISSUE TITLE
Downsampling frametimes chart data + lowpass filter

### ISSUE THREAD

**Issue by DevTechProfile** [DevTechProfile/CapFrameX#96]
Downsampling chart data to improve performance. Because downsampling causes aliasing of any frequencies in the original signal, the input signal may need to be first lowpass-filtered to prevent this aliasing.

https://www.dsprelated.com/freebooks/sasp/Filtering_Downsampling.html

**Comment by DevTechProfile** [comment]
Maybe a simple "max-strategy" would be better than a lowpass filter. Peaks should not be attenuated in any kind.

s_i+k= max(s_i, s_i+1, ..., s_i+k+1)

**Comment by Taxxor90** [comment]
Trigger downsampling when sample size is above 20.000 as first try.

**Comment by xcasxcursex** [comment]
I'm not seeing any performance issues here. Perhaps I'm missing something. I haven't done any extremely complex comparisons.

> Peaks should not be attenuated in any kind.

Definitely don't want to lowpass out stutter :) Likewise, it would be bad to max out areas of higher performance (troughs). Unfortunately, any kind of downsampling will always be lossy and that's obviously not desirable for analysis purposes.

Perhaps it is worth considering where the performance problem comes from, in the processing of the data, rather than reducing the dataset to be processed. 

....But like I said, I'm not seeing any performance issues with CX on my end.

**Comment by Taxxor90** [comment]
> I'm not seeing any performance issues here. Perhaps I'm missing something. I haven't done any extremely complex comparisons.
Then do something like 10 minutes of a game with 100 avg fps and you should see it^^

**Comment by xcasxcursex** [comment]
Going to give that a test today, but that's only 60k samples and from what I gather, oxyplot should be able to handle far more than that. I've read reports of 100K samples updating at 150Hz in realtime without issue. I'm plotting over 100K in javascript in a browser - a far less performant solution - without issue.

Are you guys sure that the size of the dataset is the _primary_ cause of the issue? Or is it possible that there's an underlying performance problem that becomes more apparent with larger datasets?

**Comment by DevTechProfile** [comment]
@xcasxcursex Which CPU do you use?

**Comment by xcasxcursex** [comment]
A 5820K with a very mild overclock. Nothing fancy by today's measure (still gets the job done in games, so it's hanging around haha)

I had a very brief look at your code and the guidelines for oxyplot and you're doing it the most performant way, according to them. I mean, my forte is embedded C, not Windows GUI C# so I don't know about WPF much ;) but I don't see anything wrong jumping out at me. I guess I'm trying to say, I'm not in any way casting doubt upon your work. I'm in no position to do that because I don't know enough about the toolchain..... But it does kinda seem like it should work and that does leave me wondering why it doesn't.

**Comment by DevTechProfile** [comment]
We will profile the code...
